# manifests/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-audit-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::835384818260:role/portfolio-pod-s3-reader